#!/usr/bin/env pwsh

# Migration script to configure terraform.tfvars and run SPA manager

# clean.ps1 should be run before this script to ensure a clean state
Remove-Item -ErrorAction SilentlyContinue .terraform.lock.hcl, imports.tf, management_summary.md, provider.tf, spa_resources.tf, terraform.tfstate, terraform.tfstate.backup, tfplan

Remove-Item -ErrorAction SilentlyContinue -Recurse .terraform

# Customer configuration variables, will migrate SPA configuration from customer_a to customer_b
$customer_a = ""
$customer_b = ""
$reset_customer_b_before_migration = $true # Set to true to reset customer_b resources before migration

# Create terraform.tfvars with the first configuration
@"
# Terraform variables for SPA resource discovery
# Generated by migrate.ps1

customer_id = "$customer_a"
base_url    = "https://api.cloud.com/accessSecurity"
client_id     = ""
client_secret = ""
"@ | Set-Content -Path terraform.tfvars

Write-Host "Created terraform.tfvars with first configuration"

# Run the SPA manager discovery command
Write-Host "Running SPA manager discovery..."
& .\spa_manager.ps1 -List

# Verify spa_resources.tf exists and replace customer_id references
if (Test-Path spa_resources.tf) {
    Write-Host "Found spa_resources.tf, replacing customer_id references..."
    $content = Get-Content -Path spa_resources.tf -Raw
    $content = $content -replace [regex]::Escape($customer_a), $customer_b
    # if customer_a has not migrated to CEP yet but customer_b is CEP enabled, we need to also
    # add gmails to allow policy creation in customer_b, since CEP feature requires emails in policies, e.g.
    #$content = $content -replace [regex]::Escape("`"OID:/ad/$customer_b`:de056bc8-519f-4b3f-ab8d-cbca469d51e4`""), "`"OID:/ad/$customer_b`:de056bc8-519f-4b3f-ab8d-cbca469d51e4`",`"EMAIL:/03fc0b3d/user1@gmail.com`""
    Set-Content -Path spa_resources.tf -Value $content -NoNewline
    Write-Host "Replaced all occurrences of '$customer_a' with '$customer_b'"
} else {
    Write-Host "WARNING: spa_resources.tf not found, skipping replacement"
    exit 1
}

# Replace terraform.tfvars with the second configuration
@"
# Terraform variables for SPA resource discovery
# Generated by migrate.ps1

customer_id = "$customer_b"
base_url    = "https://api.cloud.com/accessSecurity"
client_id     = ""
client_secret = ""

"@ | Set-Content -Path terraform.tfvars

Write-Host "Updated terraform.tfvars with second configuration"

# delete the imports.tf file to avoid conflicts
if (Test-Path imports.tf) {
    Remove-Item imports.tf
    Write-Host "Deleted imports.tf to avoid conflicts"
}

# Reset customer_b resources if flag is set
if ($reset_customer_b_before_migration) {
    Write-Host "Resetting customer_b resources before migration..."
    # backup spa_resources.tf and imports.tf of customer_a
    Move-Item -Path spa_resources.tf -Destination spa_resources.tf.bak -Force
    # Move-Item -Path imports.tf -Destination imports.tf.bak -Force

    # Run the SPA manager discovery command for customer_b
    & .\spa_manager.ps1 -List
    & .\spa_manager.ps1 -Apply
  
    # create empty spa_resources.tf to clean up resources
    Remove-Item imports.tf, spa_resources.tf
    New-Item -Path spa_resources.tf -ItemType File | Out-Null
    # run apply to delete all resources for customer_b
    & .\spa_manager.ps1 -Apply
    Write-Host "Reset completed for customer_b"
    # restore configuration of customer_a (spa_resources.tf)
    Move-Item -Path spa_resources.tf.bak -Destination spa_resources.tf -Force
    # Move-Item -Path imports.tf.bak -Destination imports.tf -Force
}

# Run the SPA manager apply command
# Write-Host "Running SPA manager apply..."
& .\spa_manager.ps1 -Apply
