# Complete spa_resources.tf with all required attributes
# Generated by SPA Manager

# Routing Domains
resource "citrixspa_routing_domain" "east" {
  fqdn         = "east.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["11111111-1111-1111-1111-000000000001"]
}

resource "citrixspa_routing_domain" "west" {
  fqdn         = "west.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["11111111-1111-1111-1111-000000000002"]
}

resource "citrixspa_routing_domain" "both" {
  fqdn         = "both.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["11111111-1111-1111-1111-000000000001", "11111111-1111-1111-1111-000000000002"]
}

resource "citrixspa_routing_domain" "none" {
  fqdn         = "none.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = []
}

resource "citrixspa_routing_domain" "orphan" {
  fqdn         = "orphan.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["11111111-1111-1111-1111-00000000000f"]
}

resource "citrixspa_routing_domain" "nameless_a" {
  fqdn         = "nameless-a.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["11111111-1111-1111-1111-00000000000e"]
}

resource "citrixspa_routing_domain" "nameless_b" {
  fqdn         = "nameless-b.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["11111111-1111-1111-1111-00000000000e"]
}

resource "citrixspa_routing_domain" "mixedcase" {
  fqdn         = "mixedcase.example.com"
  type         = "TYPE_DOMAIN"
  location_ids = ["AAAA1111-1111-1111-1111-00000000000A"]
}

# Applications
resource "citrixspa_application" "Golden_Web_App" {
  name = "Golden Web App"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC East"
      uuid = "11111111-1111-1111-1111-000000000001"
    }
  ]
}

resource "citrixspa_application" "Golden_SaaS_App" {
  name = "Golden SaaS App"
  type = "TYPE_SAAS"
  locations = [
    {
      name = "DC East"
      uuid = "11111111-1111-1111-1111-000000000001"
    },
    {
      name = "DC West"
      uuid = "11111111-1111-1111-1111-000000000002"
    }
  ]
}

resource "citrixspa_application" "Conflicting_Name_App" {
  name = "Conflicting Name App"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC South"
      uuid = "11111111-1111-1111-1111-000000000003"
    }
  ]
}

resource "citrixspa_application" "Conflicting_Name_App_Two" {
  name = "Conflicting Name App Two"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC South Renamed"
      uuid = "11111111-1111-1111-1111-000000000003"
    }
  ]
}

resource "citrixspa_application" "Case_Rename_App" {
  name = "Case Rename App"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC North"
      uuid = "11111111-1111-1111-1111-000000000004"
    }
  ]
}

resource "citrixspa_application" "Case_Rename_App_Two" {
  name = "Case Rename App Two"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC NORTH"
      uuid = "11111111-1111-1111-1111-000000000004"
    }
  ]
}

resource "citrixspa_application" "Mixed_Case_Uuid_App" {
  name = "Mixed Case Uuid App"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC Mixed"
      uuid = "aaaa1111-1111-1111-1111-00000000000a"
    }
  ]
}

resource "citrixspa_application" "Singleton_Location_App" {
  name = "Singleton Location App"
  type = "TYPE_WEB"
  locations = [
    {
      name = "DC Solo"
      uuid = "11111111-1111-1111-1111-00000000000d"
    }
  ]
}

# Access Policies
resource "citrixspa_access_policy" "Alice_Policy_One" {
  name     = "Alice Policy One"
  active   = true
  priority = 1
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      advanced_settings = {
        domain_overrides = [
          {
            fqdn         = "east.example.com"
            location_ids = ["11111111-1111-1111-1111-000000000001"]
            type         = "TYPE_DOMAIN"
          }
        ]
      },
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/00000000-0000-0000-0000-000000000001", "SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001"]
          metadata   = { "Alice Smith" = "OID:/azuread/00000000-0000-0000-0000-000000000001,SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Alice_Policy_Two" {
  name     = "Alice Policy Two"
  active   = true
  priority = 2
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/00000000-0000-0000-0000-000000000001", "SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001"]
          metadata   = { "Alice Smith" = "OID:/azuread/00000000-0000-0000-0000-000000000001,SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Alice_And_Bob_Policy" {
  name     = "Alice And Bob Policy"
  active   = true
  priority = 3
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/00000000-0000-0000-0000-000000000001", "SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001", "OID:/azuread/00000000-0000-0000-0000-000000000002"]
          metadata   = { "Alice Smith" = "OID:/azuread/00000000-0000-0000-0000-000000000001,SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001", "Bob Jones" = "OID:/azuread/00000000-0000-0000-0000-000000000002" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Everyone_Policy" {
  name     = "Everyone Policy"
  active   = true
  priority = 4
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["Everyone", "GRP:/corp/$${1 + 1}"]
          metadata   = {}
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Order_Mismatch_Policy" {
  name     = "Order Mismatch Policy"
  active   = true
  priority = 5
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001", "OID:/azuread/00000000-0000-0000-0000-000000000001"]
          metadata   = { "Alice Smith" = "OID:/azuread/00000000-0000-0000-0000-000000000001,SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Partial_Metadata_Policy" {
  name     = "Partial Metadata Policy"
  active   = true
  priority = 6
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/00000000-0000-0000-0000-000000000002", "EMAIL:/e2e/unlisted@example.com"]
          metadata   = { "Bob Jones" = "OID:/azuread/00000000-0000-0000-0000-000000000002" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Condition_Platform_Pc_Policy" {
  name     = "Condition Platform Pc Policy"
  active   = true
  priority = 7
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      conditions = [
        {
          platform_filter = "PLATFORM_FILTER_PC"
        }
      ],
      rules = []
    }
  ]
}

resource "citrixspa_access_policy" "Condition_Empty_Platform_Policy" {
  name     = "Condition Empty Platform Policy"
  active   = true
  priority = 8
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      conditions = [
        {
          platform_filter = ""
        }
      ],
      rules = []
    }
  ]
}

resource "citrixspa_access_policy" "Condition_Platform_Mac_Policy" {
  name     = "Condition Platform Mac Policy"
  active   = true
  priority = 9
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      conditions = [
        {
          platform_filter = "PLATFORM_FILTER_MAC"
        }
      ],
      rules = []
    }
  ]
}

resource "citrixspa_access_policy" "Name_Case_Policy_A" {
  name     = "Name Case Policy A"
  active   = true
  priority = 10
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/aaaaaaaa-0000-0000-0000-00000000000a"]
          metadata   = { "Sales Team" = "OID:/azuread/aaaaaaaa-0000-0000-0000-00000000000a" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Name_Case_Policy_B" {
  name     = "Name Case Policy B"
  active   = true
  priority = 11
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/aaaaaaaa-0000-0000-0000-00000000000a"]
          metadata   = { "SALES TEAM" = "OID:/azuread/aaaaaaaa-0000-0000-0000-00000000000a" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Hcl_Keyword_Policy" {
  name     = "Hcl Keyword Policy"
  active   = true
  priority = 12
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_USERGROUP"
          operator   = "OPERATOR_IN"
          tag_source = ""
          tag_key    = ""
          values     = ["OID:/azuread/cccccccc-0000-0000-0000-00000000000c"]
          metadata   = { "for" = "OID:/azuread/cccccccc-0000-0000-0000-00000000000c" }
        }
      ]
    }
  ]
}

resource "citrixspa_access_policy" "Tag_Sigil_Policy" {
  name     = "Tag Sigil Policy"
  active   = true
  priority = 13
  apps     = []
  access_rules = [
    {
      name = "rule-1",
      rules = [
        {
          type       = "TYPE_DEVICE_POSTURE"
          operator   = "OPERATOR_IN"
          tag_source = "posture/$${1 + 1}"
          tag_key    = "%%{if true}pwn%%{endif}"
          values     = ["compliant"]
          metadata   = {}
        }
      ]
    }
  ]
}

# Session Policies
resource "citrixspa_session_policy" "Golden_Session_Policy" {
  name     = "Golden Session Policy"
  active   = true
  priority = 1
  generic_rules = [
    {
      name = "session-rule-1"
      condition = [
        {
          type     = "TYPE_USERGROUP"
          operator = "OPERATOR_IN"
          values   = ["OID:/azuread/00000000-0000-0000-0000-000000000001", "SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001"]
          metadata = { "Alice Smith" = "OID:/azuread/00000000-0000-0000-0000-000000000001,SID:/example.com/S-1-5-21-1111111111-2222222222-3333333333-1001" }
        }
      ]
    }
  ]
}


resource "citrixspa_session_policy" "Empty_Token_Session_Policy" {
  name     = "Empty Token Session Policy"
  active   = true
  priority = 2
  generic_rules = [
    {
      name = "session-rule-1"
      condition = [
        {
          type     = "TYPE_USERGROUP"
          operator = "OPERATOR_IN"
          values   = ["OID:/azuread/%%{if true}pwn%%{endif}"]
          metadata = { "Empty Token Grp" = "OID:/azuread/bbbbbbbb-0000-0000-0000-00000000000b," }
        }
      ]
    }
  ]
}


# Security Groups
resource "citrixspa_security_group" "Sigil_Group" {
  name    = "Sigil $${Group}"
  app_ids = [citrixspa_application.Golden_Web_App.id]
  system = {
    data_in  = "enabled"
    data_out = "%%{if true}disabled%%{endif}"
  }
  unpublished_app = {
    data_in  = "$${var.leak}"
    data_out = "disabled"
  }
}

# Browser Modes
resource "citrixspa_browser_mode" "browser_mode" {
  browser_mode = "embedded-$${1 + 1}"
}

# Terminate Machine Access Resources
resource "citrixspa_terminate_machine_access" "tma_Sigil_Machine_if_true_pwn_endif" {
  account_name  = "svc-$${1 + 1}"
  name          = "Sigil Machine %%{if true}pwn%%{endif}"
  dns_host_name = "host-$${1 + 1}.example.com"
  domain_name   = "example.com"
  object_id     = "S-1-5-21-$${1 + 1}"
  idp_type      = "IDP_AZURE_AD"
  duration      = 3600
}

# Terminate User Access Resources
resource "citrixspa_terminate_user_access" "tua_alice_1_1_example_com" {
  account_name = "alice-%%{if true}pwn%%{endif}"
  email        = "alice+$${1 + 1}@example.com"
  domain_name  = "example.com"
  object_id    = "00000000-0000-0000-0000-$${1 + 1}"
  idp_type     = "IDP_AZURE_AD"
  duration     = 1800
}


