#!/usr/bin/env bash
# =============================================================================
# SPA Terraform Provider — migrate E2E manual cleanup
# =============================================================================
# Destroys the resources left behind by a `KEEP_RESOURCES=1` migrate run:
#   - tenant A via the e2e/ harness state
#   - tenant B via the spa_manager state under resource-listing-tool/
# then runs the API sweep on both tenants as a fallback.
#
# Credentials come from e2e/terraform.tfvars (tenant A = standard keys,
# tenant B = *_b keys) or the CITRIX_*/CITRIX_*_B environment variables.
# =============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
E2E_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROVIDER_DIR="$(cd "${E2E_DIR}/.." && pwd)"
TOOL_DIR="${PROVIDER_DIR}/resource-listing-tool"
GOLDEN_DIR="${E2E_DIR}/customer-a"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[C-migrate-cleanup]${NC} $1"; }
warn()  { echo -e "${YELLOW}[C-migrate-cleanup]${NC} $1"; }

TFVARS="${E2E_DIR}/terraform.tfvars"
load_tfvar() { grep -E "^[[:space:]]*$1[[:space:]]*=" "$TFVARS" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | head -1; }
if [ -f "${TFVARS}" ]; then
  : "${CITRIX_CUSTOMER_ID:=$(load_tfvar citrix_customer_id)}"
  : "${CITRIX_CLIENT_ID:=$(load_tfvar citrix_client_id)}"
  : "${CITRIX_CLIENT_SECRET:=$(load_tfvar citrix_client_secret)}"
  : "${CITRIX_CUSTOMER_ID_B:=$(load_tfvar citrix_customer_id_b)}"
  : "${CITRIX_CLIENT_ID_B:=$(load_tfvar citrix_client_id_b)}"
  : "${CITRIX_CLIENT_SECRET_B:=$(load_tfvar citrix_client_secret_b)}"
  : "${SPA_BASE_URL:=$(load_tfvar base_url)}"
  : "${SPA_TOKEN_URL:=$(load_tfvar token_url)}"
fi
BASE_URL="${SPA_BASE_URL:-https://api.cloud.com/accessSecurity}"
TOKEN_URL="${SPA_TOKEN_URL:-https://api.cloud.com}"

# The destroys need the locally-built provider via the filesystem mirror.
# Normally .terraformrc is generated by run-migrate-e2e.sh; create a minimal one
# here (it is git-ignored) so this cleanup can also be run standalone.
TERRAFORMRC="${E2E_DIR}/.terraformrc"
if [ ! -f "${TERRAFORMRC}" ]; then
  PLUGIN_DIR="${TF_PLUGIN_DIR:-$HOME/.terraform.d/plugins}"
  info "Generating ${TERRAFORMRC} (filesystem mirror for citrix/citrixspa)..."
  cat > "${TERRAFORMRC}" <<EOF
provider_installation {
  filesystem_mirror { path = "${PLUGIN_DIR}" include = ["registry.terraform.io/citrix/citrixspa"] }
  direct { exclude = ["registry.terraform.io/citrix/citrixspa"] }
}
EOF
fi
export TF_CLI_CONFIG_FILE="${TERRAFORMRC}"

info "Destroying Customer A golden (customer-a/ state)..."
( cd "${GOLDEN_DIR}" \
    && TF_VAR_citrix_customer_id="${CITRIX_CUSTOMER_ID}" \
       TF_VAR_citrix_client_id="${CITRIX_CLIENT_ID}" \
       TF_VAR_citrix_client_secret="${CITRIX_CLIENT_SECRET}" \
       terraform destroy -auto-approve -input=false ) || warn "Customer A destroy errored"

info "Destroying tenant B (spa_manager state)..."
( cd "${TOOL_DIR}" && terraform destroy -auto-approve -input=false ) || warn "tenant B destroy errored"

info "API sweep fallback on both tenants..."
( cd "${E2E_DIR}" && PREFIX="e2e" \
    CITRIX_CUSTOMER_ID="${CITRIX_CUSTOMER_ID}" CITRIX_CLIENT_ID="${CITRIX_CLIENT_ID}" CITRIX_CLIENT_SECRET="${CITRIX_CLIENT_SECRET}" \
    SPA_BASE_URL="${BASE_URL}" SPA_TOKEN_URL="${TOKEN_URL}" ./cleanup.sh ) || warn "tenant A sweep errored"
( cd "${E2E_DIR}" && PREFIX="e2e" \
    CITRIX_CUSTOMER_ID="${CITRIX_CUSTOMER_ID_B}" CITRIX_CLIENT_ID="${CITRIX_CLIENT_ID_B}" CITRIX_CLIENT_SECRET="${CITRIX_CLIENT_SECRET_B}" \
    SPA_BASE_URL="${BASE_URL}" SPA_TOKEN_URL="${TOKEN_URL}" ./cleanup.sh ) || warn "tenant B sweep errored"

info "Cleanup done."
