package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// SSOModel represents the SSO configuration for an application.
// All possible SSO fields across all SSO types (saml, form, kerberos, basic, nosso)
// are included. Fields not applicable to the chosen SSO type should be left null.
type SSOModel struct {
	// Universal — always present
	Type types.String `tfsdk:"type"`

	// SAML user-provided fields
	SamlType         types.String `tfsdk:"saml_type"`
	SpInitiatedOnly  types.Bool   `tfsdk:"sp_initiated_only"`
	AssertionURL     types.String `tfsdk:"assertion_url"`
	Audience         types.String `tfsdk:"audience"`
	RelayState       types.String `tfsdk:"relay_state"`
	SignAssertion    types.String `tfsdk:"sign_assertion"`
	NameIDSource     types.String `tfsdk:"name_id_source"`
	NameIDFormat     types.String `tfsdk:"name_id_format"`
	CustomAttributes types.List   `tfsdk:"custom_attributes"` // list of CustomAttributeModel

	// SAML server-computed fields (read-only, generated by backend)
	SamlSSOLoginURL    types.String `tfsdk:"saml_sso_login_url"`
	SamlCertIssuerName types.String `tfsdk:"saml_cert_issuer_name"`

	// Form SSO fields
	ActionURL     types.String `tfsdk:"action_url"`
	LogonformURL  types.String `tfsdk:"logonform_url"`
	UsernameField types.String `tfsdk:"username_field"`
	PasswordField types.String `tfsdk:"password_field"`
	Attribute     types.String `tfsdk:"attribute"`

	// Shared fields (Form, Kerberos, Basic)
	UsernameFormat types.String `tfsdk:"username_format"`

	// Kerberos fields
	UserRealm types.String `tfsdk:"user_realm"`

	// Server-computed metadata
	Customer types.String `tfsdk:"customer"`
}

// CustomAttributeModel represents a SAML custom attribute entry.
type CustomAttributeModel struct {
	Format     types.String `tfsdk:"format"`
	Name       types.String `tfsdk:"name"`
	Value      types.String `tfsdk:"value"`
	PrefixExpr types.Bool   `tfsdk:"prefix_expr"`
}

// customAttributeAttrTypes defines the Terraform attribute types for a custom attribute object.
var customAttributeAttrTypes = map[string]attr.Type{
	"format":      types.StringType,
	"name":        types.StringType,
	"value":       types.StringType,
	"prefix_expr": types.BoolType,
}

// CustomAttributeObjectType is the types.ObjectType for custom_attributes list elements.
var CustomAttributeObjectType = types.ObjectType{AttrTypes: customAttributeAttrTypes}

// ssoAttrTypes defines the Terraform attribute types for the SSO SingleNestedAttribute.
// This must match the schema defined in resource_application.go exactly.
var ssoAttrTypes = map[string]attr.Type{
	"type":                  types.StringType,
	"saml_type":             types.StringType,
	"sp_initiated_only":     types.BoolType,
	"assertion_url":         types.StringType,
	"audience":              types.StringType,
	"relay_state":           types.StringType,
	"sign_assertion":        types.StringType,
	"name_id_source":        types.StringType,
	"name_id_format":        types.StringType,
	"custom_attributes":     types.ListType{ElemType: CustomAttributeObjectType},
	"saml_sso_login_url":    types.StringType,
	"saml_cert_issuer_name": types.StringType,
	"action_url":            types.StringType,
	"logonform_url":         types.StringType,
	"username_field":        types.StringType,
	"password_field":        types.StringType,
	"attribute":             types.StringType,
	"username_format":       types.StringType,
	"user_realm":            types.StringType,
	"customer":              types.StringType,
}

// SSOObjectType is the types.ObjectType for the SSO nested attribute.
var SSOObjectType = types.ObjectType{AttrTypes: ssoAttrTypes}

// ssoModelToObject converts an *SSOModel to a types.Object that Terraform can store.
// Returns types.ObjectNull if model is nil.
func ssoModelToObject(ctx context.Context, model *SSOModel) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	if model == nil {
		return types.ObjectNull(ssoAttrTypes), diags
	}

	attrValues := map[string]attr.Value{
		"type":                  model.Type,
		"saml_type":             model.SamlType,
		"sp_initiated_only":     model.SpInitiatedOnly,
		"assertion_url":         model.AssertionURL,
		"audience":              model.Audience,
		"relay_state":           model.RelayState,
		"sign_assertion":        model.SignAssertion,
		"name_id_source":        model.NameIDSource,
		"name_id_format":        model.NameIDFormat,
		"custom_attributes":     model.CustomAttributes,
		"saml_sso_login_url":    model.SamlSSOLoginURL,
		"saml_cert_issuer_name": model.SamlCertIssuerName,
		"action_url":            model.ActionURL,
		"logonform_url":         model.LogonformURL,
		"username_field":        model.UsernameField,
		"password_field":        model.PasswordField,
		"attribute":             model.Attribute,
		"username_format":       model.UsernameFormat,
		"user_realm":            model.UserRealm,
		"customer":              model.Customer,
	}

	obj, d := types.ObjectValue(ssoAttrTypes, attrValues)
	diags.Append(d...)
	return obj, diags
}

// ssoObjectToModel converts a types.Object back to an *SSOModel for use in ssoToAPI.
// Returns nil if the object is null or unknown.
func ssoObjectToModel(ctx context.Context, obj types.Object) (*SSOModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	if obj.IsNull() || obj.IsUnknown() {
		return nil, diags
	}

	model := &SSOModel{}
	d := obj.As(ctx, model, basetypes.ObjectAsOptions{})
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return model, diags
}

// ssoFromAPI converts an API SSO map to an SSOModel.
// Server-internal fields (application_id) are silently skipped.
func ssoFromAPI(ctx context.Context, apiSSO map[string]any) (*SSOModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	if len(apiSSO) == 0 {
		return nil, diags
	}

	model := &SSOModel{}

	// Helper: get string value from map by key.
	getStr := func(key string) types.String {
		if v, ok := apiSSO[key]; ok && v != nil {
			if s, ok := v.(string); ok {
				return types.StringValue(s)
			}
		}
		return types.StringNull()
	}

	// Helper: get bool value from map by key.
	getBool := func(key string) types.Bool {
		if v, ok := apiSSO[key]; ok && v != nil {
			if b, ok := v.(bool); ok {
				return types.BoolValue(b)
			}
		}
		return types.BoolNull()
	}

	// Universal
	model.Type = getStr("type")

	// If the API returned a non-empty map but without a valid "type", the SSO
	// data is effectively unusable. Return nil so callers set ObjectNull rather
	// than storing an object with type = null, which would violate the schema
	// (type is Required on the resource).
	if model.Type.IsNull() {
		return nil, diags
	}

	// SAML user-provided
	model.SamlType = getStr("saml_type")
	model.SpInitiatedOnly = getBool("sp_initiated_only")
	model.AssertionURL = getStr("assertion_url")
	model.Audience = getStr("audience")
	model.RelayState = getStr("relay_state")
	model.SignAssertion = getStr("sign_assertion")
	model.NameIDSource = getStr("name_id_source")
	model.NameIDFormat = getStr("name_id_format")

	// SAML server-computed
	model.SamlSSOLoginURL = getStr("saml_sso_login_url")
	model.SamlCertIssuerName = getStr("saml_cert_issuer_name")

	// Form
	model.ActionURL = getStr("action_url")
	model.LogonformURL = getStr("logonform_url")
	model.UsernameField = getStr("username_field")
	model.PasswordField = getStr("password_field")
	model.Attribute = getStr("attribute")

	// Shared
	model.UsernameFormat = getStr("username_format")

	// Kerberos
	model.UserRealm = getStr("user_realm")

	// Server-computed metadata
	model.Customer = getStr("customer")

	// Custom attributes (SAML-specific)
	model.CustomAttributes = customAttributesFromAPI(ctx, apiSSO, &diags)

	return model, diags
}

// customAttributesFromAPI extracts custom_attributes from the API SSO map.
// Handles both native arrays and JSON-encoded string representations (API quirk).
func customAttributesFromAPI(ctx context.Context, apiSSO map[string]any, diags *diag.Diagnostics) types.List {
	rawValue, _ := apiSSO["custom_attributes"]

	if rawValue == nil {
		return types.ListNull(CustomAttributeObjectType)
	}

	// Handle JSON-encoded string (API sometimes returns "[]" instead of [])
	if strVal, ok := rawValue.(string); ok {
		if strings.HasPrefix(strVal, "[") {
			var parsed []any
			if err := json.Unmarshal([]byte(strVal), &parsed); err == nil {
				rawValue = parsed
			} else {
				tflog.Warn(ctx, "Failed to parse custom_attributes JSON string", map[string]any{"value": strVal, "error": err.Error()})
				return types.ListNull(CustomAttributeObjectType)
			}
		} else {
			return types.ListNull(CustomAttributeObjectType)
		}
	}

	// Handle native array
	arr, ok := rawValue.([]any)
	if !ok {
		return types.ListNull(CustomAttributeObjectType)
	}

	if len(arr) == 0 {
		listValue, listDiag := types.ListValue(CustomAttributeObjectType, []attr.Value{})
		diags.Append(listDiag...)
		return listValue
	}

	elements := make([]attr.Value, 0, len(arr))
	for _, elem := range arr {
		objMap, ok := elem.(map[string]any)
		if !ok {
			continue
		}

		attrValues := map[string]attr.Value{
			"format":      types.StringNull(),
			"name":        types.StringNull(),
			"value":       types.StringNull(),
			"prefix_expr": types.BoolNull(),
		}

		if v, ok := objMap["format"]; ok && v != nil {
			attrValues["format"] = types.StringValue(fmt.Sprintf("%v", v))
		}
		if v, ok := objMap["name"]; ok && v != nil {
			attrValues["name"] = types.StringValue(fmt.Sprintf("%v", v))
		}
		if v, ok := objMap["value"]; ok && v != nil {
			attrValues["value"] = types.StringValue(fmt.Sprintf("%v", v))
		}
		if v, ok := objMap["prefix_expr"]; ok && v != nil {
			if b, ok := v.(bool); ok {
				attrValues["prefix_expr"] = types.BoolValue(b)
			}
		}

		objValue, objDiag := types.ObjectValue(customAttributeAttrTypes, attrValues)
		diags.Append(objDiag...)
		elements = append(elements, objValue)
	}

	listValue, listDiag := types.ListValue(CustomAttributeObjectType, elements)
	diags.Append(listDiag...)
	return listValue
}

// ssoToAPI converts an SSOModel to an API SSO map for POST/PUT requests.
// Server-computed fields (saml_sso_login_url, saml_cert_issuer_name) are excluded.
func ssoToAPI(ctx context.Context, model *SSOModel) (map[string]any, diag.Diagnostics) {
	var diags diag.Diagnostics

	if model == nil {
		return nil, diags
	}

	result := make(map[string]any)

	// Helper: set string in map if not null/unknown.
	setStr := func(key string, val types.String) {
		if !val.IsNull() && !val.IsUnknown() {
			result[key] = val.ValueString()
		}
	}
	// Helper: set bool in map if not null/unknown.
	setBool := func(key string, val types.Bool) {
		if !val.IsNull() && !val.IsUnknown() {
			result[key] = val.ValueBool()
		}
	}

	// Universal
	setStr("type", model.Type)

	// SAML user-provided
	setStr("saml_type", model.SamlType)
	setBool("sp_initiated_only", model.SpInitiatedOnly)
	setStr("assertion_url", model.AssertionURL)
	setStr("audience", model.Audience)
	setStr("relay_state", model.RelayState)
	setStr("sign_assertion", model.SignAssertion)
	setStr("name_id_source", model.NameIDSource)
	setStr("name_id_format", model.NameIDFormat)

	// Deliberately NOT including server-computed fields:
	//   saml_sso_login_url, saml_cert_issuer_name
	// Sending them causes TypeError in the backend's SamlProperties.__init__().

	// Form
	setStr("action_url", model.ActionURL)
	setStr("logonform_url", model.LogonformURL)
	setStr("username_field", model.UsernameField)
	setStr("password_field", model.PasswordField)
	setStr("attribute", model.Attribute)

	// Shared
	setStr("username_format", model.UsernameFormat)

	// Kerberos
	setStr("user_realm", model.UserRealm)

	// Custom attributes
	if !model.CustomAttributes.IsNull() && !model.CustomAttributes.IsUnknown() {
		var customAttrs []CustomAttributeModel
		d := model.CustomAttributes.ElementsAs(ctx, &customAttrs, false)
		diags.Append(d...)
		if !diags.HasError() {
			apiAttrs := make([]map[string]any, len(customAttrs))
			for i, ca := range customAttrs {
				a := make(map[string]any)
				if !ca.Format.IsNull() && !ca.Format.IsUnknown() {
					a["format"] = ca.Format.ValueString()
				}
				if !ca.Name.IsNull() && !ca.Name.IsUnknown() {
					a["name"] = ca.Name.ValueString()
				}
				if !ca.Value.IsNull() && !ca.Value.IsUnknown() {
					a["value"] = ca.Value.ValueString()
				}
				if !ca.PrefixExpr.IsNull() && !ca.PrefixExpr.IsUnknown() {
					a["prefix_expr"] = ca.PrefixExpr.ValueBool()
				}
				apiAttrs[i] = a
			}
			result["custom_attributes"] = apiAttrs
		}
	}

	return result, diags
}
